# Generated by Django 3.2.3 on 2023-12-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contnet',
            new_name='contet',
        ),
    ]
